version: "2"
run:
  concurrency: 4
  modules-download-mode: mod
  tests: false
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - gosec
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        text: 'G101:'
      - linters:
          - gosec
        text: 'G108:'
      - linters:
          - gosec
        text: 'G109:'
      - linters:
          - gosec
        text: 'G110:'
      - linters:
          - gosec
        text: 'G204:'
      - linters:
          - gosec
        text: 'G306:'
      - linters:
          - gosec
        text: 'G402:'
      - linters:
          - gosec
        text: 'G404:'
      - linters:
          - gosec
        text: 'G601:'
    paths:
      - tools
      - examples
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - tools
      - examples
      - third_party$
      - builtin$
      - examples$
