# Copyright (c) 2021 Terminus, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

run:
  concurrency: 4
  timeout: 2m
  modules-download-mode: mod
  # include test files or not, default is true
  tests: false
  allow-parallel-runners: true
  skip-dirs:
  skip-files:

linters-settings:
  goimports:
#    local-prefixes: github.com/erda-project/erda-infra

linters:
  disable-all: true
  # 修复完 issues 后再增加新的 linter
  enable:
    - goimports
    - gosec
    - gofmt

issues:
  exclude-rules:
    - linters:
        - gosec
      text: "G101:" # G101: Potential hardcoded credentials (gosec)
    - linters:
        - gosec
      text: "G108:" # G108: Profiling endpoint is automatically exposed on /debug/pprof (gosec)
    - linters:
        - gosec
      text: "G109:" # G109: Potential Integer overflow made by strconv.Atoi result conversion to int16/32 (gosec)
    - linters:
        - gosec
      text: "G110:" # G110: Potential DoS vulnerability via decompression bomb (gosec)
    - linters:
        - gosec
      text: "G204:" # G204: Subprocess launched with function call as argument or cmd arguments (gosec)
    - linters:
        - gosec
      text: "G306:" # G306: Expect WriteFile permissions to be 0600 or less
    - linters:
        - gosec
      text: "G402:" # G402: TLS InsecureSkipVerify may be true. (gosec)
    - linters:
        - gosec
      text: "G404:" # G404: Use of weak random number generator (math/rand instead of crypto/rand) (gosec)
    - linters:
        - gosec
      text: "G601:" # G601: Implicit memory aliasing in for loop. (gosec)