POST localhost:8080/api/component-protocol/actions/render
Content-Type: application/json

{
  "scenario": {
    "scenarioKey": "parallel-demo"
  },
  "inParams": {
    "startTime": 1234,
    "endTime": 4321
  }
}