// Code generated by protoc-gen-go-http. DO NOT EDIT.
// Source: user.proto

package pb

import (
	context "context"
	http1 "net/http"

	http "github.com/erda-project/erda-infra/pkg/transport/http"
	urlenc "github.com/erda-project/erda-infra/pkg/urlenc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the "github.com/erda-project/erda-infra/pkg/transport/http" package it is being compiled against.
const _ = http.SupportPackageIsVersion1

// UserServiceHandler is the server API for UserService service.
type UserServiceHandler interface {
	// get user
	// GET /api/user/{id}
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	// update user
	// PUT /api/user/{id}
	UpdateUser(context.Context, *GetUserRequest) (*UpdateUserResponse, error)
}

// RegisterUserServiceHandler register UserServiceHandler to http.Router.
func RegisterUserServiceHandler(r http.Router, srv UserServiceHandler, opts ...http.HandleOption) {
	h := http.DefaultHandleOptions()
	for _, op := range opts {
		op(h)
	}
	type ConvertFunc func(http1.ResponseWriter, *http1.Request) (interface{}, error)
	encodeFunc := func(fn ConvertFunc) http.HandlerFunc {
		return func(w http1.ResponseWriter, r *http1.Request) {
			out, err := fn(w, r)
			if err != nil {
				h.Error(w, r, err)
				return
			}
			if err := h.Encode(w, r, out); err != nil {
				h.Error(w, r, err)
			}
		}
	}

	convert_GetUser_to_HandlerFunc := func(fn func(context.Context, *GetUserRequest) (*GetUserResponse, error)) ConvertFunc {
		handler := func(ctx context.Context, req interface{}) (interface{}, error) {
			return fn(ctx, req.(*GetUserRequest))
		}
		if h.Interceptor != nil {
			handler = h.Interceptor(handler)
		}
		return func(w http1.ResponseWriter, r *http1.Request) (interface{}, error) {
			var in GetUserRequest
			if err := h.Decode(r, &in); err != nil {
				return nil, err
			}
			var input interface{} = &in
			if u, ok := (input).(urlenc.URLValuesUnmarshaler); ok {
				if err := u.UnmarshalURLValues("", r.URL.Query()); err != nil {
					return nil, err
				}
			}
			out, err := handler(r.Context(), &in)
			if err != nil {
				return out, err
			}
			return out, nil
		}
	}

	convert_UpdateUser_to_HandlerFunc := func(fn func(context.Context, *GetUserRequest) (*UpdateUserResponse, error)) ConvertFunc {
		handler := func(ctx context.Context, req interface{}) (interface{}, error) {
			return fn(ctx, req.(*GetUserRequest))
		}
		if h.Interceptor != nil {
			handler = h.Interceptor(handler)
		}
		return func(w http1.ResponseWriter, r *http1.Request) (interface{}, error) {
			var in GetUserRequest
			if err := h.Decode(r, &in); err != nil {
				return nil, err
			}
			var input interface{} = &in
			if u, ok := (input).(urlenc.URLValuesUnmarshaler); ok {
				if err := u.UnmarshalURLValues("", r.URL.Query()); err != nil {
					return nil, err
				}
			}
			out, err := handler(r.Context(), &in)
			if err != nil {
				return out, err
			}
			return out, nil
		}
	}

	r.Add("GET", "/api/user/{id}", encodeFunc(convert_GetUser_to_HandlerFunc(srv.GetUser)))
	r.Add("PUT", "/api/user/{id}", encodeFunc(convert_UpdateUser_to_HandlerFunc(srv.UpdateUser)))
}
