// Code generated by protoc-gen-go-client. DO NOT EDIT.
// Source: greeter.proto, user.proto

package client

import (
	context "context"
	pb "github.com/erda-project/erda-infra/examples/service/protocol/pb"
	grpc "github.com/erda-project/erda-infra/pkg/transport/grpc"
	grpc1 "google.golang.org/grpc"
)

// Client provide all service clients.
type Client interface {
	// GreeterService greeter.proto
	GreeterService() pb.GreeterServiceClient
	// UserService user.proto
	UserService() pb.UserServiceClient
}

// New create client
func New(cc grpc.ClientConnInterface) Client {
	return &serviceClients{
		greeterService: pb.NewGreeterServiceClient(cc),
		userService:    pb.NewUserServiceClient(cc),
	}
}

type serviceClients struct {
	greeterService pb.GreeterServiceClient
	userService    pb.UserServiceClient
}

func (c *serviceClients) GreeterService() pb.GreeterServiceClient {
	return c.greeterService
}

func (c *serviceClients) UserService() pb.UserServiceClient {
	return c.userService
}

type greeterServiceWrapper struct {
	client pb.GreeterServiceClient
	opts   []grpc1.CallOption
}

func (s *greeterServiceWrapper) SayHello(ctx context.Context, req *pb.HelloRequest) (*pb.HelloResponse, error) {
	return s.client.SayHello(ctx, req, s.opts...)
}

type userServiceWrapper struct {
	client pb.UserServiceClient
	opts   []grpc1.CallOption
}

func (s *userServiceWrapper) GetUser(ctx context.Context, req *pb.GetUserRequest) (*pb.GetUserResponse, error) {
	return s.client.GetUser(ctx, req, s.opts...)
}

func (s *userServiceWrapper) UpdateUser(ctx context.Context, req *pb.UpdateUserRequest) (*pb.UpdateUserResponse, error) {
	return s.client.UpdateUser(ctx, req, s.opts...)
}
