name: CI AND IT
on:
  push:
    tags:
      - v*
    branches:
      - develop
      - master
      - release/*
  pull_request:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22
      - name: Run Lint
        uses: golangci/golangci-lint-action@v3
      - name: Run Test
        run: |
          echo $GOARCH
          go test -cpu=2 -timeout 10s -race -coverprofile=coverage.txt -covermode=atomic ./...
      - name: Check coverage file
        run: |
          ls -la coverage.txt || echo "coverage.txt not found"
          head -10 coverage.txt || echo "coverage.txt empty or not readable"
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
          fail_ci_if_error: true
          flags: unittests
          name: codecov-umbrella
          verbose: true
          slug: erda-project/erda-infra
  CODE-CHECK:
    runs-on: ubuntu-latest
    container:
      image: registry.erda.cloud/erda/erda-base:20240410
    steps:
      - uses: actions/checkout@v2
      - name: Run go mod tidy
        run: make tidy
      - name: Run Go Lint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.49.0
          golangci-lint run --timeout=15m ./...
      # - name: Run Go Vet
      #   run: go vet ./...
