name: CI AND IT
on:
  push:
    tags:
      - v*
    branches:
      - develop
      - master
      - release/*
  pull_request:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: Run Lint
        uses: golangci/golangci-lint-action@v3
      - name: Run Test
        run: |
          go test -cpu=2 -timeout 10s -race -coverprofile=coverage.txt -covermode=atomic ./...
          bash <(curl -s https://codecov.io/bash)
  CODE-CHECK:
    runs-on: ubuntu-latest
    container:
      image: recallsong/golang-base:210416
    steps:
      - uses: actions/checkout@v2
      - name: Run go mod tidy
        run: make tidy
      - name: Run Go Lint
        run: |
          go get -u golang.org/x/lint/golint
          golint -set_exit_status=1 ./...
      # - name: Run Go Vet
      #   run: go vet ./...
